[2024-06-01T01:00:15.539+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: crawl_stock_data.create_table_and_insert_task scheduled__2024-05-31T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-06-01T01:00:15.562+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
